# Exported from Render on 2026-09-25T14:07:47Z
version: "1"
services:
- type: web
  name: ZenithHub
  runtime: python
  repo: https://github.com/jerzy12323/ZenithHub
  plan: 0.5c-512mb
  envVars:
  - key: DISCORD_WEBHOOK_URL
    sync: false
  - key: SMTP_USER
    sync: false
  - key: SMTP_PORT
    sync: false
  - key: SMTP_PASSWORD
    sync: false
  - key: SMTP_HOST
    sync: false
  - key: PUBLIC_URL
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: GOOGLE_REDIRECT_URI
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false
  - key: MAIL_FROM
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: DATA_DIR
    sync: false
  - key: PYTHON_VERSION
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt && python -m py_compile server.py
  startCommand: python server.py
  healthCheckPath: /api/mods
  disk:
    name: beammods-data
    mountPath: /var/data
    sizeGB: 10
  autoDeployTrigger: commit
